### ISSUE TITLE
VCV Rack crashes and instantly closes on my computer when I add ORBsq Vi to the patch

### ISSUE THREAD

**Issue by rucascampeoum** [gwygonik/ORBsqVi#3] opened 2024-11-01 19:59 UTC
It's literally what I describe, I select the module on my library and the program closes itself.

My laptop is a Lenovo Legion 5 15ARH05 running Windows 10 Home

Other specs:
Processor: AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
RAM:	16,0 GB

**Comment by gwygonik** [comment] 2024-11-01 20:17
Thanks for reporting. I'd need a log file from your laptop to help track down the issue, as I can't reproduce this problem on my Windows 10 computer. You should be able to find the log file located at C:/Users/<your user name>/AppData/Local/Rack2/log.txt

I'd suggest launching Rack, try to add the module, then after it closes grab the log file. The very bottom of it should have the error information as to why it crashed.

If you can get me that, we can see of that helps me track down what the problem is and we can get it running! 😃

**Comment by rucascampeoum** [comment] 2024-11-01 20:41
I got an e-mail notification so we can communicate through here exclusively.

I just opened my recently crashed VCV Rack and tried adding the module to the empty patch and it just appeared as is supposed to. When loading a new patch with my template and trying to add it there it worked again.

The only difference this time was the audio interface I'm using was already loaded on the Audio module. So, I thought the issue only happens when I'm not connected to an audio interface, which never happened to me with other modules. However, with no interface connected it's still working this time.

I'm trying to force the error but it's not happening. I'll play with the module now that I can and I'll try to get the error again soon and I'll upload a new log file if it happens.

Here's the current log file, meanwhile. I don't know if it has information about any recent crash

[log.txt](https://github.com/user-attachments/files/17603975/log.txt)

**Comment by gwygonik** [comment] 2024-11-01 20:48
This is GREAT information, actually! I've seen reports that the Windows version of Rack has an issue with reporting the audio interface's sample rate to modules. ORBsq _does_ look at the sample rate to set the speed of drift. 

I'm guessing your crash is probably related to this. I will see what the latest is on this matter and see if there's anything I can do to guard against it.

Thank you! 😃

**Comment by gwygonik** [comment] 2024-11-01 20:57
An update to this: it appears that Windows does _sometimes_ report the samplerate at startup as 0, which creates problems when trying to set properties based on that value. I can definitely guard against this! I'll push an update, though it will be a few days.

Thanks for the report and helping track this down!

**Comment by rucascampeoum** [comment] 2024-11-01 21:40
I'm glad I could be of help! And I'm happy it's working for me anyways for now.

**Comment by gwygonik** [comment] 2024-11-01 22:41
I'm not going to close this until after the next update goes through, and then we can see if you have any more problems.

**Comment by gwygonik** [comment] 2024-11-04 23:42
2.0.4 is in the library today, and should fix this issue! (Not that you're having it any longer) I'll let this stay open for a few days, just in case. Thanks again for reporting the problem!

**Closed as completed** 2024-11-11 23:43 UTC
